#ifndef __BOARD_SERVICE_COMMAND_H__
#define __BOARD_SERVICE_COMMAND_H__

enum service_on_board_command
{
    POST_WRITE_SERVICE_ON_BOARD_EXECUTE,
    SERVICE_ON_BOARD_END
};

#define SERVICE_ON_BOARD_EXECUTE_BUFFER_COUNT         (SERVICE_ON_BOARD_END)
#define SERVICE_ON_BOARD_EXECUTE_BUFFER               ((SERVICE_ON_BOARD_END) - 1)

#endif
